apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: websocket-backendconfig
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60
  customRequestHeaders:
    Upgrade: "$http_upgrade"
    Connection: "upgrade"
