apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ticketing-cert
  namespace: default
spec:
  secretName: ticketing-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: ticketing.dev
  dnsNames:
    - ticketing.dev
