apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: harun1809030/ticketing-auth
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: MONGO_URI_TICKETS
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: JWT_KEY
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
