apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: harun1809030/ticketing-client
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: NEXT_PUBLIC_JWT_KEY
            - name: NEXT_PUBLIC_STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: NEXT_PUBLIC_STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  namespace: default
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      