apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
type: Opaque
data:
  JWT_KEY: c2VjcmV0S2V5MTIzIQ==
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVJjWXhiUHV2eEw0cGVNVHB3QWtLbUZhNktJS0tLeE92TWdsT1JzTEdhUUFlUGVxQmhOTXdLenk1TXFXSTZnQUN3VkxXSGptZFdWM1Bhd1V0ZTQ2Y3A0UzAwUjRsMHVaMng=
