apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: harun1809030/ticketing-tickets
          ports:
            - containerPort: 3000
          env:
            - name: DEBUG
              value: "socket.io*"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom: 
                secretKeyRef: 
                  name: cluster-secrets
                  key: MONGO_URI_TICKETS
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLIENT_URL
              valueFrom: 
                secretKeyRef:
                  name: cluster-secrets
                  key: CLIENT_URL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
